apiVersion: v1
kind: Service
metadata:
  name: lux-operator
  namespace: lux-system
  labels:
    app: lux-operator
spec:
  selector:
    app: lux-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
    - name: health
      port: 8081
      targetPort: 8081
  type: ClusterIP
