apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: luxchains.lux.network
spec:
  group: lux.network
  scope: Namespaced
  names:
    plural: luxchains
    singular: luxchain
    kind: LuxChain
    shortNames:
      - luxchain
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: ChainID
          type: string
          jsonPath: .status.chainId
        - name: BlockchainID
          type: string
          jsonPath: .status.blockchainId
      schema:
        openAPIV3Schema:
          type: object
          description: LuxChain tracks (and optionally orchestrates) chain deployments and syncing.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
